### ISSUE TITLE
File replacement doesn't want to work

### ISSUE THREAD

**Issue by Ronaldo-Venancio** [FUComplete/Patch#101]
Interestingly, I have the same problem as Pedro, I followed the detailed step-by-step instructions to replace the files, I identified the root of "PPSSPP", I created the "FUC" folder, I put "config.bin" there -- - I made some modifications to the text for testing in "str_tbl.pac" (without changing bits or word order) and I did all the steps until generating the "nativePSP" folder and placed the folder in "FUC", in the same folder as "Config.bin" --- In FuComplete.exe I went to "configure", selected "config.bin" and put it in "MS0". However, nothing happened within the game, this also applies to the modification of other files I made, none of them worked, and like Pedro, I have no idea how to replace the direct file from "data.bin".

Well, I've been following your incredible work for a long time and I tried to contact you in several ways, but I couldn't. Anyway, I'm a little guy with a lot of free time and who has already translated some games into my language (Brazilian Portuguese), such as Bornout dominator, Downhill Domination, Shrek team Action and other small jobs such as book translations. The game I most want to translate is, without a doubt, Monster Hunter Freedom Unite, as it was part of my childhood, but I had no idea how to decrypt the “data.bin” file, much less how to compress it. When I discovered your work, I believed it was my only chance to translate the game, unfortunately I didn't find another way to get in touch with you, and well, if it's possible, I would be very grateful if you would allow me to translate the game from your patch, it would be almost a dream, and I would be even more grateful if you could lend me the tool you used to help with the translation.

I don't know if the problem is my PPSSPP configuration, maybe it's its version, I don't know if that influences it... (I use PPSSPP Gold version 1.16.6). PPSSPP Root folder after following the tutorial

![Captura de tela 2023-12-18 191945](https://github.com/FUComplete/Patch/assets/154280165/41cac6a4-6e7e-4f3b-b219-515567681b7d)

**Comment by IncognitoMan** [comment]
Will be fixed in 1.4.0.
