### ISSUE TITLE
Pokke Farm Gathering Bug

### ISSUE THREAD

**Issue by PatrickWeylin** [FUComplete/Patch#102]
When gathering from mining or bug catching spots, the final gathering attempt almost always returns "there is nothing else here". I never experienced this on 1.3.1, but this happens very frequently on 1.4.0.
![ULJM05500_00000](https://github.com/FUComplete/Patch/assets/160848797/8cfd4142-5f68-4667-9a10-a7281d8e47a6)

**Comment by IncognitoMan** [comment]
It's not a bug but happens because of hold to gather/carve. It's really non-issue other than telling you there's nothing else to gather/mine.
