### ISSUE TITLE
[Feature Request] Minimal bugfix-only patch to maintain Hunsterverse community compatibility

### ISSUE THREAD

**Issue by headHz** [FUComplete/Patch#11]
Is there any chance you could release a minimal patch that would just fix the graphical/math bugs ( issues #2 and #7) for MHP2G that would leave the rest of the game untouched? No translation, save converting, or quest-adding needed. That way the game would still be compatible with the online Hunsterverse servers while only one party is patched. 

Thanks for your time.

**Comment by IncognitoMan** [comment]
Sorry for the late reply... been busy and was mulling it over.

Answered in #13 but to sum it up... I have no intentions as of this time to create a separate patch to maintain HV compat. If Zack adds whats needed to allow cross play I'll update it to allow it.
