### ISSUE TITLE
[Bug Report] Translated JP quests, information errors

### ISSUE THREAD

**Issue by Abbanon** [FUComplete/Patch#42]
# [No.23] Magazine: Tyranny of Tigrex
It's missing punctuation here, seems like there should be a `.` present.
![ULJM05500_00000](https://user-images.githubusercontent.com/37251822/165244816-402c2b43-a190-40de-8625-2a36d516bc59.png)

# [No.34] JUMP: Emperor of Explosions
Client's name spills off of the page and out of the screen. Maybe abbreviate it to `One-Eyed,BlackBeardedMan`?
![ULJM05500_00001](https://user-images.githubusercontent.com/37251822/165245099-6af4d13f-3a0b-45d2-aa4a-e74a5ab487a4.png)

**Comment by IncognitoMan** [comment]
Nice catch...

Fixed, redownload the release.
