### ISSUE TITLE
[Feature Request] Monster Hunter F1Complete patch for Monster Hunter Portable 1st

### ISSUE THREAD

**Issue by Hydra-Spectre** [FUComplete/Patch#45]
The Japanese version of Portable 2nd G/Freedom Unite is often seen as the superior version with having more content.
The same could be said for its lesser-known predecessor Monster Hunter Portable 1st/Freedom 1.
A smaller patch porting Freedom 1's translation to Portable 1st would be great, especially since it would bring forth some QoL changes similar to FUComplete and Portable 3rd HD Ver., while making the controls for the Portable/Freedom Trilogy unified with O as confirm and X as cancel.

**Comment by Instandhaltung** [comment]
Lol, gotta increase the item box and item stack capacity then. This was the main reason why I never really got into MHF1 😂

**Comment by IrunaBasics** [comment]
Any news on this? Mhp1 english patch and mhp2 (not mhp2g) english patch iso?

**Comment by SilverJolteon** [comment]
> Any news on this? Mhp1 english patch and mhp2 (not mhp2g) english patch iso?

In case you haven't already seen, I ported them over.
[Portable](https://github.com/SilverJolteon/FreedomDX)
[Portable 2nd (WIP)](https://github.com/SilverJolteon/MHP2-English-Patch/tree/main/latest_build)

**Comment by IrunaBasics** [comment]
sorry friend i dont know how todo  this guide. its easier to just someone do the iso translated and i download. i can wait. also thank you.
