### ISSUE TITLE
[FEATURE REQUEST] Permanent Elder Dragon quest on elder / nekoht / Guild hall

### ISSUE THREAD

**Issue by 3b1l** [FUComplete/Patch#46]
The elder dragon quest sometimes appear and disappear which is annoying also sometimes you fight the elder dragon in a different arena for example kushala daora you fight in snowy mountain next is the jungle make it so it's a different quest mission.

**Comment by 3b1l** [comment]
##
![c2j333a73rs81 png](https://user-images.githubusercontent.com/94207616/166659894-609fa44a-ccc0-4cab-9448-d6bb559b9018.png)

**Comment by 3b1l** [comment]
![Uploading Screenshot_2022-05-04-17-58-21-169_org.ppsspp.ppsspp.jpg…]()

**Comment by 3b1l** [comment]
![Uploading Screenshot_2022-05-04-17-58-21-169_org.ppsspp.ppsspp.jpg…]()

**Comment by 3b1l** [comment]
![Uploading Screenshot_2022-05-04-17-53-04-637_org.ppsspp.ppsspp.png…]()

**Comment by 3b1l** [comment]
![Uploading 4h1wl5n33rs81.png.png…]()

**Comment by 3b1l** [comment]
![Uploading c2j333a73rs81.png.png…]()

**Comment by 3b1l** [comment]
[
![Screenshot_2022-05-04-17-56-26-538_org ppsspp ppsspp](https://user-images.githubusercontent.com/94207616/166661641-eaf542a5-2a46-4a09-87d5-df7cc11e49c3.png)

**Comment by 3b1l** [comment]
![Screenshot_2022-05-04-17-53-04-637_org ppsspp ppsspp](https://user-images.githubusercontent.com/94207616/166661693-e44d5fae-cb1f-45b0-86b8-845716952666.png)

**Comment by 3b1l** [comment]
![Screenshot_2022-05-04-17-58-21-169_org ppsspp ppsspp](https://user-images.githubusercontent.com/94207616/166661737-4839b16f-9c8c-4791-9cb8-97cc6604f122.png)

**Comment by ftw28** [comment]
I think that's actually normal. 
Normally you do some damage to it, then it leaves and you complete the quest. At some point, a new quest appears where you can finish it off.
