### ISSUE TITLE
[Feature Request] Minimal "quality checking" patch that just fixes the known errors in Portable 2nd G

### ISSUE THREAD

**Issue by padoverc** [FUComplete/Patch#51]
The main patch has gone past fixes and is now modifying the actual gameplay experience. I was hoping for a more basic patch (perhaps an .xdelta even?) that just makes the game look and play as the original Japanese developers intended (and likely would have fixed themselves if they had had more time.) 

Ideally it would be made to:

- Fix any known graphical bugs, such as the exclamation point in the equipment crafting screen, or the guildcard felyne's ear color.
- Ensure all 'special quests' give the correct rewards, and that the quest triggers in the first place.
- Does not alter anything involving the DOWNLOADS(Event/Challenge Quests, bonus items/titles) or INSTALL(not needing to hit select) Main-Menu options in order to maintain strict PSP console compatability.
- Nothing else.

Rather than an "FU Complete" patch, I am hoping for a "P2G QC'd" patch. Just the little sprinkling of fixes that can take a great game to the level of perfection.

**Comment by AsteriskAmpersand** [comment]
Seconding that this sounds great! As you said, this sounds quite different from a "FU Complete" patch, so probably would have to be a separate repository and project. Will you be the one taking the initiative to start this project, or is there a group you are working with on this? Very excited to see what work you bring forward from this.

**Comment by padoverc** [comment]
I don't know how to do any of that. All the things mentioned were found and fixed by this patch's dev. I was just hoping there would be a way to make a patch with just those fixes, and without all the other stuff.
