### ISSUE TITLE
Make changing the keys optional

### ISSUE THREAD

**Issue by beefucurry** [FUComplete/Patch#52]
""Standard" control layout (X/O are swapped, meaning O = Accept / X = Cancel)"  I'd like to use this patch, but like many who have played MHFU for over 1000 hours, saying "you can only use this patch if you accept the buttons no longer do what you are practiced them doing" is a deal breaker.

**Comment by AsteriskAmpersand** [comment]
You can remap controllers on your emulator of choice.

**Comment by KKiller450** [comment]
This change would be greatly appreciated among my group that plays. We would love to use this patch, but our muscle memories are convincing us not to. Either way, thank you for contribution towards improving this game! This patch is awesome.
