### ISSUE TITLE
[Feature Request?] Adding more custom quest slot

### ISSUE THREAD

**Issue by floydGG** [FUComplete/Patch#53]
Is it possible to add more custom quest,  or remove original custom quest that already in the patch?

**Comment by IncognitoMan** [comment]
It's actually planned for 1.3... currently fully implemented with an in-game toggle to switch between built-in events and up to 18 slots in savedata. I still need to translate the english strings to japanese for the toggle/description of the setting and also have an app to easily inject quests into savedata...

I've just not had as much time as I'd like to work on stuff and still have a bit more planned for 1.3 before a release but it is planned at least...

Here's a video showing how it works currently:

https://user-images.githubusercontent.com/5410031/200043156-45578ebb-c634-434b-8653-4f4f2701a4b1.mp4

**Comment by floydGG** [comment]
This looks so cool ngl, awesome job really.
Do u still need cwcheat to activate that features? or is it prebuilt?

**Comment by IncognitoMan** [comment]
It's built-in, so no cwcheat to activate it... I'll hopefully have more things moved to being part of the code rather than as a cwcheat.

**Comment by Satomi12** [comment]
> It's actually planned for 1.3... currently fully implemented with an in-game toggle to switch between built-in events and up to 18 slots in savedata. I still need to translate the english strings to japanese for the toggle/description of the setting and also have an app to easily inject quests into savedata...
> 
> I've just not had as much time as I'd like to work on stuff and still have a bit more planned for 1.3 before a release but it is planned at least...
> 
> Here's a video showing how it works currently:
> 
>  Peek_2022-07-18_02-38.mp4

Hi, is there a way to get a japanese language version like this?
