### ISSUE TITLE
[Bug Report] Translation string: Alignment issues

### ISSUE THREAD

**Issue by Abbanon** [FUComplete/Patch#56]
The following menus have misaligned text strings in FUC, they should be properly centered:
![ULJM05500_00003](https://user-images.githubusercontent.com/37251822/209704502-5c815672-09df-429c-b8ae-ea248513de21.png)
![ULJM05500_00005](https://user-images.githubusercontent.com/37251822/209704503-c410a126-1e04-44e2-adae-323eedfca91d.png)

**Comment by IncognitoMan** [comment]
![Image](https://user-images.githubusercontent.com/5410031/209773409-5b9e0aef-1473-412d-bd22-07e267d773ad.jpg)

Fixed the "Character selected"
