### ISSUE TITLE
[Feature Request] Remove pulsing effect from Quest HUD sharpness icon/have static sharpness glow effect

### ISSUE THREAD

**Issue by Abbanon** [FUComplete/Patch#60]
Normally, the weapon sharpness indicator on the quest HUD slowly pulses in and out to show the current sharpness of your weapon.
It would be pretty useful to remove the pulsating effect entirely, instead having it as a static glow visible at all times.
![Screenshot_1](https://user-images.githubusercontent.com/37251822/209734428-d4dc5837-4196-4567-a4c3-127fab8f4d42.png)

**Comment by IncognitoMan** [comment]
Closing as #61 fixes the alignment issues and really wouldn't want to remove the pulsating effect...
