### ISSUE TITLE
[Bug Report/Vanilla Issue] Quest HUD Sharpness icon inconsistencies

### ISSUE THREAD

**Issue by Abbanon** [FUComplete/Patch#61]
- The glow around Green (and up) sharpness extends around the top and right edge of the blade icon
- The glow around Green (and up) sharpness does not cover a few pixels along the bottom of the blade icon

![Screenshot_4](https://user-images.githubusercontent.com/37251822/209744265-b1fdff6e-f5d1-4f55-a56d-86175eb1e9e9.png)

- The low sharpness icon (jagged, Orange & Red) is more narrow than the default sharpness icon by 1px along the bottom
- The glow around Red sharpness extends around all sides of the blade icon

![Screenshot_3](https://user-images.githubusercontent.com/37251822/209744396-4a3dce37-3b53-4598-a871-a9f10d193400.png)
![Screenshot_2](https://user-images.githubusercontent.com/37251822/209744397-34ae818a-5dc1-453e-a1d1-63ff1a4faf6a.png)

**Comment by IncognitoMan** [comment]
![image](https://user-images.githubusercontent.com/5410031/215670131-b2a6b0fa-d9fe-42bc-97f2-46cf3a981b47.png)
![image](https://user-images.githubusercontent.com/5410031/215670146-72d6cb6b-d834-4edb-8402-c36869da1092.png)

Hopefully this is acceptable...
