### ISSUE TITLE
[Bug Report] Full equipment box anywhere causes animation issues in Pokke Farm and Felyne Kitchen

### ISSUE THREAD

**Issue by Abbanon** [FUComplete/Patch#85]
If you change any of your equipment at the Pokke Farm or Felyne Kitchen item boxes using FUC's full chest access, your player model will skip any animations in those areas until you leave and re-enter.

This applies to:
- All spots in the Farm that prompt player animations (mining points, bug bushes, etc.)
- Eating at the table in the Kitchen

If you interact with any points in the Farm after changing equipment, your inputs will lock up for the 1-2 seconds it normally takes for any animation to play. However, your character just stands there. Inputs are freed up again afterwards.
Also if you interact with the Kitchen table, your character will be stuck running up against the table until you select your ingredients and eat.

![ULJM05500_00009](https://user-images.githubusercontent.com/37251822/222165585-ec524646-d7ae-4403-8178-89ea9c149b52.png)

**Comment by IncognitoMan** [comment]
Fixed in 1.3.0a
