### ISSUE TITLE
[Bug Report] Text Overflow For Bowgun Capacity (1.3.0a)

### ISSUE THREAD

**Issue by ChallengeHunter** [FUComplete/Patch#86]
In the capacity tab for bowguns the text overflows in the latest update.
![ULJM05500_00000](https://user-images.githubusercontent.com/126848277/222636299-09a9ebd5-b0fd-4ef1-9ece-fd66c4b93857.png)
![ULJM05500_00001](https://user-images.githubusercontent.com/126848277/222636305-6da2a14f-6f9b-45ca-896d-52a9532a22b6.png)

**Comment by IncognitoMan** [comment]
Which weapon is that? As everything looks fine on my end... 
![ULJM05500_00036](https://user-images.githubusercontent.com/5410031/222637901-83211d55-6cb7-4977-b098-e506f6153b30.png)

**Comment by ChallengeHunter** [comment]
Seems to happen with every bowgun for me, I'll check if it's related to my save file.

**Comment by IncognitoMan** [comment]
Do you have any cheats enabled?

**Comment by ChallengeHunter** [comment]
Yeah, I forgot to disable the cheats from v1.2.1 it indeed was the cause of the text overflow. Thanks for the help.

**Comment by alextirzx** [comment]
Hello and good day. I would like to know how could I go about fixing this same issue when already advanced into the game.

I just reached G Rank, and noticed the text overflow on all bowguns.
