### ISSUE TITLE
Does this include all the downloadable event quests?

### ISSUE THREAD

**Issue by Darthagnon** [FUComplete/Patch#9]
Just thought I'd double check, since the readme says the event quests are included - does this patch include all the downloadable event quests? Do they replace any of the built-in quests?

I bought MHFU way back in the day from PSN; just wondering if this is the definitive way to play the game with the DLC and Japan-exclusive armours/items included...

**Comment by Darthagnon** [comment]
I've been using the [MHFU Save Tools](http://forums.ppsspp.org/showthread.php?tid=5476) until now

**Comment by IncognitoMan** [comment]
> Just thought I'd double check, since the readme says the event quests are included - does this patch include all the downloadable event quests? Do they replace any of the built-in quests?

Yes, the patch adds the event DLC quests into the guild hall. You will find them in their respective ranks... so for example the 3* `Its name is "Mega Kut-Ku"!?` is found in the 3* section. If you are wondering which quests are added in... as well as their respective "star" rank [please refer to this](https://github.com/FUComplete/Patch/wiki/Quests)

As for if it replaces any of the built-in quests? No... all the original quests are there with the event quests added on top in their respective rank as mentioned above.

>I've been using the MHFU Save Tools until now
EDIT: Just saw in the Projects that Challenge Quests aren't included yet.
Wondering, I guess Trenya, Poogie outfits, travelling Felyne Comrade Barrel are activated, too?

Challenge quest are a bit of a headache to add because of the code handling training hall (challenge quests are the ones you'd fight in training hall). The hope is that there will be a bit of a streamlined way to inject the challenge quests into the save for 1.1 until a better solution is found.

For bonus DLC content like trenya and such... [there's a cheat code for this to enable it on your save](https://github.com/FUComplete/Patch/wiki/Enhancements-and-BonusDLC#bonus-dlc).

>I bought MHFU way back in the day from PSN; just wondering if this is the definitive way to play the game with the DLC and Japan-exclusive armours/items included...

If you want translated japan-exclusive armors/items/events, p2g based code (x/o not swapped and uncensored blood) and all the actual event quests built-in this is what the patch accomplishes. The only downside is making it so patched can not connect to unpatched and vice versa.

**Comment by Darthagnon** [comment]
That sounds amazing! Thank you so much for answering my questions, and your work on the project! I'll try it out, and look forward to the future of this project. I remember using TempAR cheat codes on the PSP for bigger blood and JP-exclusive items.

Is it ok if I ask another couple of dumb questions?

**Install data** - it always annoyed me, having to use an extra 800MB or so, just to get item previews in the in-game shop. Do you know if install data is actual uncompressed game data required for the previews, or just a flag that could be flipped with a cheat code, so you can have the benefits without sacrificing storage?

**HUD off** - I used to use a TempAR cheat code in MHP3rd which toggled the HUD and Map display off (displayed when LTrigger is held) until the player HP dropped below a certain level (I can hunt it down in my ```cheats.db``` on my other HDD if you like). I remember experimenting a few years ago (2015ish), searching memory values on the PSP, trying to get something similar for MHFU/MHP2ndG, but never got better than making the HP/Stamina flicker. You/your team probably know more about the inner workings of MHFU than anyone else (public); any idea if this is possible in MHFU? I know the menu option exists in-game, but could never figure out how to target it with a cheat code.

**Comment by IncognitoMan** [comment]
> Install data - it always annoyed me, having to use an extra 800MB or so, just to get item previews in the in-game shop. Do you know if install data is actual uncompressed game data required for the previews, or just a flag that could be flipped with a cheat code, so you can have the benefits without sacrificing storage?

Actually already investigated this a bit.... sadly there's been only partial success. So far the only results I've had have been 1.) having it start with weapon preview by default but doesn't update/load the weapon itself, 2.) having it start and preview the first weapon correctly but doesn't flush the result and eventually leads to a overflow/crash or 3.) complains that there's no install data. 

Will probably look more into it but for now its been pushed back for other things.

> HUD off - I used to use a TempAR cheat code in MHP3rd which toggled the HUD and Map display off (displayed when LTrigger is held) until the player HP dropped below a certain level (I can hunt it down in my cheats.db on my other HDD if you like). I remember experimenting a few years ago (2015ish), searching memory values on the PSP, trying to get something similar for MHFU/MHP2ndG, but never got better than making the HP/Stamina flicker. You/your team probably know more about the inner workings of MHFU than anyone else (public); any idea if this is possible in MHFU? I know the menu option exists in-game, but could never figure out how to target it with a cheat code.

I'll investigate that as a cheat code... should be relatively easy to implement.

**Comment by IncognitoMan** [comment]
Just an update...

Looked into the cheat you mentioned for P3rd and made one similar to it. Added it to the [wiki page](https://github.com/FUComplete/Patch/wiki/Enhancements-and-BonusDLC#hud-off-above-40-hp).

```
_C0 HUD Off Above 40 HP
_L 0xE0046167 0x0125A5A0
_L 0xE1010029 0x308AF464
_L 0x01200EBC 0x00000001
_L 0xE1010028 0x208AF464
_L 0x01200EBC 0x00000000
```

Lemme know how that works for you.

**Comment by Darthagnon** [comment]
Thank you so much for that! [I added all the cheat codes to my PSP cheats database](https://github.com/Darthagnon/my-psp-cheats), and tested the HUD-off one, but didn't have any luck. I'm guessing it's targeting MHP2ndG? (I'm still on MHFU (EU) ULES-01213 until I update)

**Comment by IncognitoMan** [comment]
I tried to port it to FU after posting the cheat but there's something preventing it from working... trying to write to the address instantly reverts it back so there's some sort of additional check that needs to be addressed. For now it'll only work on P2G.

As for your cheats.db lemme help you with that as these cheats are not interchangeable... I'm not even sure they would work with the EU version of the game but I did port a few to FU (US).

**MHFU (US) ULUS10391**
```
_C0 MinimapHack v1.0 (75%)
_L 0x10042F24 0x00003F40
_L 0x10042F28 0x00003F40
_L 0x10042F30 0x00000165
_L 0x10042F34 0x00000022
_L 0x10042F54 0x00000165
_L 0x10042F5C 0x00000022
_C0 MinimapHack v1.0 (50%)
_L 0x10042F24 0x00003F00
_L 0x10042F28 0x00003F00
_L 0x10042F30 0x00000188
_L 0x10042F34 0x00000022
_L 0x10042F54 0x00000188
_L 0x10042F5C 0x00000022

_C0 Enable Bonus DLC ( disable afterward )
// Enable cheat, go to Main Menu and select Options. Change
// any option and save. Disable cheat and revert any changes
// you made in Options menu.
// Note:
// This hooks a save prompt to delay writing the value...
// bypassing a sanity check to prevent save corruption.
// Turn off the cheat before loading your character.
_L 0xD11940F8 0x00000054
_L 0x20A504F0 0x07FFF9FF
```

Again these are for FU (US) ULUS10391... so unsure if they will work with the EU version. I don't really have any intention to keep porting codes between different regions for reasons like the HUD one that works on P2G but not FU.

**Comment by Darthagnon** [comment]
Thank you!! I've added them to the `cheat.db`. 

Do you reckon it's worth me testing RAM searches with TempAR to see if I can find that extra check memory value, or is MIPS assembly knowledge a prerequisite? I'll test the USA codes in the EU version, see if they work.

**Comment by IncognitoMan** [comment]
Looked at it again and realized I messed up and was modifying the wrong value... either way here it is ported to MHFU (US).

**MHFU (US) ULUS10391**
```
_C0 Hide HUD above 40 HP
_L 0xE0046167 0x0125F320
_L 0xE1010029 0x308B3864
_L 0x012052BC 0x00000001
_L 0xE1010028 0x208B3864
_L 0x012052BC 0x00000000
```

**Comment by Darthagnon** [comment]
Thank you!! Added to the cheat.db. I'd forgotten that Raw/Element/Status wasn't the "true" value in MHFU, but that info sounds very familiar...
