### ISSUE TITLE
[Request] Cwcheat code that allows for seeing equipment thumbnail without DATA INSTALL?

### ISSUE THREAD

**Issue by padoverc** [FUComplete/Patch#93]
I remember you had one listed in the wiki at the start. I was hoping to archive that code since I haven't seen it listed elsewhere.

**Comment by Darthagnon** [comment]
Here's the (now removed) wiki page with the cheat codes:
[Enhancements-and-BonusDLC.md](https://github.com/FUComplete/Patch/files/13629249/Enhancements-and-BonusDLC.md)

There was one more change made later, replacing the EN/JP separate codes with the following:

# True Raw/Ele/Status

```
_C0 True Raw/Ele/Status
_L 0xE0023031 0x001AE788
_L 0x001CA173 0x00000020
_L 0x001CA18A 0x00000020
_L 0xE0023530 0x001AE788
_L 0x001CABCC 0x00000020
_L 0x001CABE5 0x00000020
_L 0x40138104 0x000B0001  
_L 0x00000064 0x00000000
```
