### ISSUE TITLE
FUCTool closes itself during patching

### ISSUE THREAD

**Issue by MrLuckey** [FUComplete/Patch#94]
It simply stops working and closes itself when it reaches the DATA.BIN section.

**Comment by Hairo** [comment]
Can you try with [this build](https://send.vis.ee/download/3dc73ba819e395fd/#XS-sNhJQDWxM-czvNkjCIw)? just replace the exe file with this new one.

A file called `output.log` will be created in the same folder when you use the tool, post this file when the error happens (it won't close itself now, but an error will show up the output text and in the file)

**Comment by MrLuckey** [comment]
Oh... the output log was pretty clear to me, its actually i was low on storage space haha! Totally my fault, you can tag this as resolved ^^ you helped me see the problem. After freeing space, the patch is applying... given my slow pc, this might take a while.

**Comment by MrLuckey** [comment]
oops, i can do it myself. Cheers!
