### ISSUE TITLE
[Feature Requests] Add Monster Hunter 2 Dos Praising Sucess song.

### ISSUE THREAD

**Issue by AmyRoxwell** [FUComplete/Patch#98]
It would be neat that, when using the dos audio, the music for the Quest Complete/Reward Screen were using MH dos version instead of the one used on MHFU (MH1 quest complete)
https://www.youtube.com/watch?v=DLFLQYpBntk The song in question.

**Comment by IncognitoMan** [comment]
https://www.nexusmods.com/monsterhunterfreedomunite/mods/3

Use file replacer to generate a nativePSP to load them

Also note if you want the Dos audio while using nativePSP, be sure to extract the numbered files from the ISO in `FUC/nativePSP` (those being `6552`, `6553`, `6554`, `6555`, `6566` and `6571`) and place them in the nativePSP folder on your memstick.

**Comment by AmyRoxwell** [comment]
Thank you very much!
